export const leads = [
  {
    id: "#3071",
    name: "Eli Torres",
    company: "Nexa Logic",
    email: "eli@nexalogic.io",
    phone: "+1 (415) 221-3344",
    value: "$3,217.55",
    tag: "Important",
    source: "Twitter",
    status: "Customer",
    created: "2 min ago",
    avatar: "https://i.pravatar.cc/36?img=11",
  },
  {
    id: "#3070",
    name: "Mira Patel",
    company: "Orbit Hive",
    email: "mira@orbithive.com",
    phone: "+1 (312) 420-8890",
    value: "$6,984.20",
    tag: "Follow up",
    source: "Instagram",
    status: "Qualified",
    created: "1 hr ago",
    avatar: "https://i.pravatar.cc/36?img=12",
  },
  {
    id: "#3069",
    name: "Jonah Kim",
    company: "CoreTech",
    email: "jonah@coretech.ai",
    phone: "+1 (213) 702-3101",
    value: "$4,125.00",
    tag: "Review",
    source: "Google Ads",
    status: "Working",
    created: "5 hr ago",
    avatar: "https://i.pravatar.cc/36?img=13",
  },
  {
    id: "#3068",
    name: "Ava Nguyen",
    company: "Pulse Agency",
    email: "ava@pulseagency.io",
    phone: "+1 (646) 308-4022",
    value: "$9,100.33",
    tag: "Follow up",
    source: "Behance",
    status: "Contacted",
    created: "8 hr ago",
    avatar: "https://i.pravatar.cc/36?img=14",
  },
  {
    id: "#3067",
    name: "Liam Reyes",
    company: "Skyhook Labs",
    email: "liam@skyhooklabs.org",
    phone: "+1 (202) 908-1742",
    value: "$1,200.00",
    tag: "Review",
    source: "AngelList",
    status: "Qualified",
    created: "16 hr ago",
    avatar: "https://i.pravatar.cc/36?img=15",
  },
  {
    id: "#3060",
    name: "Sofia King",
    company: "Neon Wave",
    email: "sofia@neonwave.net",
    phone: "+1 (786) 234-9801",
    value: "$3,410.88",
    tag: "Review",
    source: "Twitter",
    status: "Proposal Sent",
    created: "2 days ago",
    avatar: "https://i.pravatar.cc/36?img=16",
  },
];
